print("..My first adding decimal calculator..")
print("")
num1 = input("Enter your First Number: ")
num2 = input("Enter your another number: ")
result = float(num1) + float(num2)
print("")
print("The total is..")
print(result)
