from math import *
my_num = -5
print("this abs tells you the absolute value which is ")
print(abs(my_num))
print("====================================================")
print("this will tell you to use two numbers at a time")
print(pow(3, 2))
print("========================================================")
print("some other math function")
print(max(4, 6))
print(min(2, 9))
print(round(3.7))
print(" it just grab the lowest number")
print(floor(3.7))
print("=================================")
print("it just round the number")
print(ceil(3.1))
print("it do square root")
print(sqrt(36))
