colour = input("Enter a colour: ")
body = input("Enter a body part: ")
name = input("Enter a celebrity name: ")
country = input("Enter a country name: ")
print("  ......MAD LIBS GAME.....")
print("")
print("Roses are " + colour)
print(body+" looks dirty ")
print("I love " + name)
print("I am from " + country)

