co = input("Enter a colour: ")
plu = input("Enter a body part: ")
na = input("Enter a celebrity name: ")
country = input("Enter a country name: ")
print("  ......MAD LIBS GAME.....")
print("")
print("Roses are " + co)
print(plu+" looks dirty ")
print("I love " + na)
print("I am from " + country)

